"""Server-side renderer for PRD § 4.5 Public Query Page.

FastAPI Jinja2 SSR (NOT Next.js — current next.config.ts is `output:
'export'`, no Node runtime in production). All pages emit
`<meta name="robots" content="noindex, follow">` per PRD § 4.5 需求 3
(2026-05-05 修訂).

PHASE A coverage: en + zh-TW. Other locales fall back to en. PHASE E
unifies i18n source-of-truth across utils/i18n-share.ts and this dict.
"""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader, select_autoescape

logger = logging.getLogger(__name__)

_TEMPLATE_DIR = Path(__file__).resolve().parent.parent / "templates"

_env = Environment(
    loader=FileSystemLoader(str(_TEMPLATE_DIR)),
    autoescape=select_autoescape(["html", "jinja2", "xml"]),
)

# Mirror of utils/i18n-share.ts surface strings. Synced manually until
# PHASE E unifies the source-of-truth. Only the strings used by the
# Public Query / Revoked / Flagged pages live here — Share Modal +
# Settings strings stay frontend-only.
_STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "publicCtaTitle": "Want to ask your own version?",
        "publicCtaButton": "Try it on Vela",
        "publicDisclaimer": (
            "This content is generated by AI from publicly available medical "
            "literature, intended for healthcare professionals as a discussion "
            "reference only. It does not constitute medical advice, diagnosis, "
            "or prescription. Do not use for self-diagnosis or self-medication. "
            "Consult a qualified healthcare provider for any health concerns."
        ),
        "publicRevoked": "This share has been revoked.",
        "publicFlagged": "This share was removed for violating the terms of service.",
        "citationsHeading": "References",
        "privacyLink": "Privacy",
        "termsLink": "Terms",
    },
    "zh-TW": {
        "publicCtaTitle": "想問你自己的版本？",
        "publicCtaButton": "在 Vela 試試",
        "publicDisclaimer": (
            "此內容由 AI 根據公開醫學文獻生成，僅供醫療專業人員參考討論，"
            "不構成醫療建議、診斷或處方。請勿用於自我診斷或自我用藥。"
            "如有健康問題請諮詢合格醫療人員。"
        ),
        "publicRevoked": "此分享已被撤回。",
        "publicFlagged": "此分享因違反使用條款已下架。",
        "citationsHeading": "參考來源",
        "privacyLink": "隱私政策",
        "termsLink": "使用條款",
    },
}

_HTML_LANG_MAP = {"en": "en", "zh-TW": "zh-Hant"}


def resolve_locale(requested: str | None) -> str:
    """PHASE A only ships en + zh-TW renderer copy. Anything else → en.

    Note: utils/i18n-share.ts already falls back to en for the other 14
    languages, so the single-locale degradation is consistent end-to-end.
    """
    if requested == "zh-TW":
        return "zh-TW"
    return "en"


def _truncate(text: str, n: int) -> str:
    text = (text or "").strip().replace("\n", " ").replace("\r", " ")
    return text if len(text) <= n else text[: n - 1].rstrip() + "…"


def _base_url() -> str:
    return os.getenv("VELA_PUBLIC_BASE_URL", "https://vela.an-tho.com").rstrip("/")


def _common_context(share, locale: str) -> dict[str, Any]:
    s = _STRINGS[locale]
    base = _base_url()
    share_id = getattr(share, "share_id", "") if share else ""
    query_text = getattr(share, "query_text", "") if share else ""
    answer_text = getattr(share, "answer_text", "") if share else ""

    return {
        "html_lang": _HTML_LANG_MAP[locale],
        "s": s,
        "share_id": share_id,
        "query_text": query_text,
        "answer_text": answer_text,
        "og_title": _truncate(query_text, 80) + " · Vela" if query_text else "Vela",
        "og_description": _truncate(answer_text, 160),
        "og_image": f"{base}/static/og/{share_id}.png" if share_id else f"{base}/static/og/default.png",
        "canonical_url": f"{base}/q/{share_id}" if share_id else base,
    }


def render_public_page(share, locale: str) -> str:
    locale = resolve_locale(locale)
    ctx = _common_context(share, locale)
    ctx["citations"] = getattr(share, "citations", None) or []
    return _env.get_template("q_public.jinja2").render(**ctx)


def render_revoked_page(locale: str, share=None) -> str:
    locale = resolve_locale(locale)
    ctx = _common_context(share, locale)
    return _env.get_template("q_revoked.jinja2").render(**ctx)


def render_flagged_page(locale: str, share=None) -> str:
    locale = resolve_locale(locale)
    ctx = _common_context(share, locale)
    return _env.get_template("q_flagged.jinja2").render(**ctx)
