"""Server-side renderer for PRD § 4.5 Public Query Page.

FastAPI Jinja2 SSR (NOT Next.js — current next.config.ts is `output:
'export'`, no Node runtime in production). All pages emit
`<meta name="robots" content="noindex, follow">` per PRD § 4.5 需求 3
(2026-05-05 修訂).

PHASE A coverage: en + zh-TW. Other locales fall back to en. PHASE E
unifies i18n source-of-truth across utils/i18n-share.ts and this dict.

UX polish 1 (2026-05-07): full alignment with main-site design system.
- Ports parseResearchSections() from pages/research.tsx so the public
  page can render evidence-strength cards with the same colored
  left-border treatment.
- Augments citations with the source-type / credibility config tables
  ported from components/CitationPanel.tsx so visitor sees the same
  source label color and credibility pill.

Dogfooding fix (2026-05-08): 5-star credibility rendering removed
from both frontend and server-side per advisor feedback. The
backend `credibility` field is preserved for Phase 1B evidence-tier
classification work — only the visual block was dropped.
"""

from __future__ import annotations

import logging
import os
import re
from collections import Counter
from html import escape as _escape
from pathlib import Path
from typing import Any

import markdown as _markdown
from jinja2 import Environment, FileSystemLoader, select_autoescape
from markupsafe import Markup

logger = logging.getLogger(__name__)

_TEMPLATE_DIR = Path(__file__).resolve().parent.parent / "templates"

_env = Environment(
    loader=FileSystemLoader(str(_TEMPLATE_DIR)),
    autoescape=select_autoescape(["html", "jinja2", "xml"]),
)

# Mirror of utils/i18n-share.ts surface strings. Synced manually until
# PHASE E unifies the source-of-truth. Only the strings used by the
# Public Query / Revoked / Flagged pages live here — Share Modal +
# Settings strings stay frontend-only.
_STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "publicCtaTitle": "Want to ask your own version?",
        "publicCtaButton": "Try it on Vela",
        "publicDisclaimer": (
            "This content is generated by AI from publicly available medical "
            "literature, intended for healthcare professionals as a discussion "
            "reference only. It does not constitute medical advice, diagnosis, "
            "or prescription. Do not use for self-diagnosis or self-medication. "
            "Consult a qualified healthcare provider for any health concerns."
        ),
        "publicShortDisclaimer": (
            "⚠️ For informational purposes only. Always verify with "
            "clinical guidelines and consult a qualified professional."
        ),
        "publicRevoked": "This share has been revoked.",
        "publicFlagged": "This share was removed for violating the terms of service.",
        "citationsHeading": "References",
        "credibilityLabel": "Credibility",
        "viewSource": "View source",
        "peerReviewed": "Peer Reviewed",
        "official": "Official",
        "internal": "Internal",
        "sourceWithdrawn": "Source withdrawn",
        "headerTagline": "Ask in your language. Verified by official sources.",
        "privacyLink": "Privacy",
        "termsLink": "Terms",
    },
    "zh-TW": {
        "publicCtaTitle": "想問你自己的版本?",
        "publicCtaButton": "在 Vela 試試",
        "publicDisclaimer": (
            "此內容由 AI 根據公開醫學文獻生成,僅供醫療專業人員參考討論,"
            "不構成醫療建議、診斷或處方。請勿用於自我診斷或自我用藥。"
            "如有健康問題請諮詢合格醫療人員。"
        ),
        "publicShortDisclaimer": (
            "⚠️ 本資訊僅供參考,請依據臨床指引並諮詢合格專業人員。"
        ),
        "publicRevoked": "此分享已被撤回。",
        "publicFlagged": "此分享因違反使用條款已下架。",
        "citationsHeading": "參考來源",
        "credibilityLabel": "可信度",
        "viewSource": "檢視來源",
        "peerReviewed": "同儕審查",
        "official": "官方來源",
        "internal": "內部資料",
        "sourceWithdrawn": "來源已撤回",
        "headerTagline": "用你的語言提問,由官方來源驗證。",
        "privacyLink": "隱私政策",
        "termsLink": "使用條款",
    },
}

_HTML_LANG_MAP = {"en": "en", "zh-TW": "zh-Hant"}


# ============================================================
# Section parser — port of parseResearchSections() in
# pages/research.tsx 61-82. Splits the answer markdown by H2 headers
# of the form:
#     ## Title 🟢 — Language
#     ## Title 🟡 — Language
#     ## Title 🔴 — Language
#     ## Title  (no marker, fallback)
# Returns a list of dicts: {title, marker, content}. If no headers
# are found, returns a single section with title=None marker=None and
# the whole answer as content (so the caller can still render a card).
# ============================================================
_HEADER_RE = re.compile(
    r"^##\s+(?P<title>.+?)(?:\s+(?P<marker>\U0001F7E2|\U0001F7E1|\U0001F534))?\s*(?:—\s*.+)?$",
    re.MULTILINE,
)

# Color table for evidence-strength markers — matches
# components/ResearchSection.tsx borderColors (lines 11-15).
# 2026-08-10 (fly 219): values moved from literal hex to CSS VARIABLES so that
# prefers-color-scheme can reach them. Dark keeps the exact shipped colours; light
# uses the app's .light severity tokens (contrast-shifted for AA on white). This is
# a THEMEABILITY change only — the colour language is unchanged in dark.
# ⚠️ NOT neutralised: components/ResearchSection.tsx:18-19 shows the main app uses a
# NEUTRAL accent (rgb(var(--color-text) / 0.15)) with no severity colour at all, so
# full convergence would drop these too. That is a medical-communication decision
# (🟢🟡🔴 conveys evidence strength) and is FLAGGED for the founder, not taken here.
_MARKER_BORDER_COLORS: dict[str | None, str] = {
    "\U0001F7E2": "var(--vela-evidence-strong)",    # 🟢 strong
    "\U0001F7E1": "var(--vela-evidence-moderate)",  # 🟡 moderate
    "\U0001F534": "var(--vela-evidence-limited)",   # 🔴 limited
    None: "var(--vela-evidence-default)",           # default slate
}


def parse_research_sections(answer_text: str) -> list[dict[str, Any]]:
    """Split an answer into evidence-strength sections.

    Mirrors the JS implementation in pages/research.tsx so the public
    page renders the same card UI a logged-in user sees on /research.
    """
    if not answer_text or not answer_text.strip():
        return [{"title": None, "marker": None, "content": ""}]

    matches = list(_HEADER_RE.finditer(answer_text))
    if not matches:
        return [{"title": None, "marker": None, "content": answer_text.strip()}]

    sections: list[dict[str, Any]] = []
    for i, m in enumerate(matches):
        title = (m.group("title") or "").strip()
        marker = m.group("marker")
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(answer_text)
        content = answer_text[start:end]
        # Strip leading "---" separator (matches JS behavior).
        content = re.sub(r"^\s*---\s*", "", content).strip()
        if content:
            sections.append({"title": title, "marker": marker, "content": content})

    if not sections:
        return [{"title": None, "marker": None, "content": answer_text.strip()}]
    return sections


def _markdown_to_html(text: str) -> str:
    """Render section content markdown → HTML for embedding inside
    the .vela-prose div in the public page. Uses python-markdown
    with the same feature set ReactMarkdown ships on the main site
    (gfm-style: fenced code, tables, breaks)."""
    if not text:
        return ""
    return _markdown.markdown(
        text,
        extensions=["extra", "sane_lists", "nl2br"],
        output_format="html",
    )


# ============================================================
# Citation source-type / credibility config — ported from
# components/CitationPanel.tsx 73-92. Same values; comment in TS
# refs back to here.
# ============================================================
_SOURCE_TYPE_CONFIG: dict[str, dict[str, str]] = {
    "pubmed":         {"label": "PubMed"},
    "fda":            {"label": "FDA"},
    "tfda":           {"label": "TFDA 核准適應症"},  # ADR 007 — scope-accurate (indication-only), own bucket
    "dailymed":       {"label": "DailyMed"},  # B-2 — US drug label (official-label family, own bucket; NOT RxNorm)
    "loinc":          {"label": "LOINC"},
    "medlineplus":    {"label": "MedlinePlus"},
    "rxnorm":         {"label": "RxNorm"},
    "who":            {"label": "WHO"},
    "nice":           {"label": "NICE"},
    "ema":            {"label": "EMA"},
    "cochrane":       {"label": "Cochrane"},
    # ⛔ LEGACY-ONLY as of 2026-07-29 (c1) — the local drug corpus is deprecated and no
    # longer retrieved, so no NEW share can carry source_type 'local'. Kept because this
    # renderer runs ON DEMAND over stored citation JSON, so already-published /q and
    # /explore pages would otherwise silently relabel ("Local" → "Source"). Verified
    # non-crashing either way (_detect_source_type falls through to "other" on an empty
    # url), but the relabel is user-visible on live URLs. NOTE: this label DISAGREES with
    # the frontend's "FDA" (utils/sourceLabels.ts) — the recorded [P2] sourceLabels ↔
    # share_renderer drift. Deprecation removes one side of that drift going forward.
    "local":          {"label": "Local"},
    "localauthority": {"label": "Local"},
    "other":          {"label": "Source"},
}

# ⛔ _CRED_CONFIG REMOVED 2026-08-10 (fly 219) — the credibility PILL is gone from
# both public surfaces, converging on the main app. `6066a92` (2026-06-10) removed it
# from CitationPanel because source_type and credibility are REDUNDANT (PubMed→
# peer-reviewed, FDA→official) and a pill reads as a QUALITY GRADE, which it is not.
# The share page carried the pre-6066a92 design for three months.
# ⚠️ The stored `credibility` FIELD is untouched — it still drives the TOMBSTONE
# (see `tombstone_citation`) and is retained for Phase 1B evidence-tier work.
# Only the visual pill is removed.



def is_local_citation(citation: dict[str, Any]) -> bool:
    """True when a stored citation is a pre-c1 `local` corpus stub.

    Uses the same detection the renderer uses, so write-side and render-side
    can never disagree about what counts as `local`.
    """
    if not isinstance(citation, dict):
        return False
    return _detect_source_type(citation) == "local"


def tombstone_citation(citation: dict[str, Any]) -> dict[str, Any]:
    """THE single definition of what tombstoning a `local` citation means.

    Rule 19 — ONE implementation, two callers: `_augment_citations` (render, for
    the 8 stubs already in prod) and `/api/share/create` (write, so no NEW
    untombstoned `local` row can ever be persisted).

    Data-level only. This deliberately does NOT bake in render chrome — no
    `source_label`, no colours — because those are LOCALE-DEPENDENT and computed
    per request ("Source withdrawn" / "來源已撤回"). Persisting a label would
    freeze one locale into the row.

    What it removes is the CLAIM, which is the actual defect:
      * `credibility` → None: no "Official" pill for an empty document.
      * `url` → "": no "View source" link offering provenance that does not exist.
    What it KEEPS: the slot, `source_type` (so the renderer still recognises and
    tombstones it), the title, and the snippet — the snippet stays visible on
    purpose, because it shows the reader *why* the slot was withdrawn (founder
    decision 2026-08-07, vindicated at the fly-216 render gate).
    """
    out = dict(citation)
    out["credibility"] = None
    out["url"] = ""
    return out


def _detect_source_type(citation: dict[str, Any]) -> str:
    """Mirror of detectSourceType() in CitationPanel.tsx 36-62.
    Falls back to URL hostname matching when source_type is missing."""
    raw = (citation.get("source_type") or "").strip().lower()
    if raw in _SOURCE_TYPE_CONFIG:
        return raw
    url = (citation.get("url") or "").lower()
    if not url:
        return "other"
    hostmap = (
        ("pubmed.ncbi.nlm.nih.gov", "pubmed"),
        ("ncbi.nlm.nih.gov/pubmed", "pubmed"),
        ("fda.gov.tw", "tfda"),   # TW TFDA — BEFORE the US fda.gov entry
        ("fda.gov", "fda"),
        ("accessdata.fda.gov", "fda"),
        ("loinc.org", "loinc"),
        ("medlineplus.gov", "medlineplus"),
        ("dailymed.nlm.nih.gov", "dailymed"),   # B-2 — DailyMed is its own official-label source (was 'rxnorm', debt-(2) drift)
        ("rxnav.nlm.nih.gov", "rxnorm"),
        ("who.int", "who"),
        ("nice.org.uk", "nice"),
        ("ema.europa.eu", "ema"),
        ("cochrane.org", "cochrane"),
        ("cochranelibrary.com", "cochrane"),
    )
    for needle, slug in hostmap:
        if needle in url:
            return slug
    return "other"


_ABSTRACT_HEADER_RE = re.compile(r"^#{1,3}\s*abstract", re.IGNORECASE)
_ABSTRACT_LABEL_RE = re.compile(
    r"^\*\*(Authors?|Journal|PMID|Background|Methods?|Results?|Conclusions?|Objective)s?\*\*",
    re.IGNORECASE,
)
_ABSTRACT_INLINE_LABEL_RE = re.compile(r"\*\*[A-Z][A-Z\s/]{1,20}:\*\*")


def _extract_abstract(raw: str) -> str:
    """Mirror of extractAbstract() in CitationPanel.tsx 110-132.
    Strips the leading `## Abstract` header and bold-label lines so
    the public page shows just the prose body."""
    if not raw:
        return ""
    lines = raw.split("\n")
    # Look for a leading "## Abstract" / "### Abstract" / "# Abstract" line
    abstract_idx = -1
    for i, line in enumerate(lines):
        if _ABSTRACT_HEADER_RE.match(line.strip()):
            abstract_idx = i
            break
    if abstract_idx != -1:
        text = " ".join(lines[abstract_idx + 1:]).strip()
    else:
        text = " ".join(
            line for line in lines
            if line.strip()
            and not line.strip().startswith("#")
            and not _ABSTRACT_LABEL_RE.match(line.strip())
        ).strip()
    text = _ABSTRACT_INLINE_LABEL_RE.sub("", text).strip()
    text = re.sub(r"\s{2,}", " ", text).strip()
    return text


def _truncate_abstract(text: str | None, n: int = 200) -> str | None:
    """Strip leading markdown header/labels, then hard truncate; no
    expand toggle on the public page (locked decision per task plan)."""
    if not text:
        return None
    cleaned = _extract_abstract(text)
    if not cleaned:
        return None
    if len(cleaned) <= n:
        return cleaned
    return cleaned[: n - 1].rstrip() + "…"


def _augment_citations(
    citations: list[dict[str, Any]] | None,
    locale: str,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """Return (augmented_citations, source_chips).

    Each augmented citation carries the precomputed display-only fields
    the template needs so the Jinja layer stays trivial: source_type
    (slug), source_label, source_color, credibility (raw key),
    abstract_truncated. No credibility pill since 2026-08-10.
    """
    if not citations:
        return [], []
    s = _STRINGS[locale]

    augmented: list[dict[str, Any]] = []
    type_counter: Counter[str] = Counter()
    for c in citations:
        if not isinstance(c, dict):
            continue
        slug = _detect_source_type(c)
        sconf = _SOURCE_TYPE_CONFIG[slug]

        # ── TOMBSTONE (open-item #7, 2026-08-07) ────────────────────────────
        # A pre-c1 `local` citation is an EMPTY STUB: every one of the 690
        # documents in the deprecated local corpus is field-label scaffolding
        # with no values (<=20 chars, max 5, median 1; the 8 rows still stored
        # on prod hold 35-64 chars of "Drug: X\n\nContraindications:\n4"), and
        # each carries `credibility: "official"` with an empty `url`.
        #
        # THE DEFECT IS THE CREDIBILITY CLAIM, NOT THE ROW'S EXISTENCE — a
        # public page presenting an empty stub under an "Official" pill.
        # So the entry is TOMBSTONED, not removed:
        #   * it KEEPS ITS SLOT and therefore its [N]. `q_public.jinja2:51`
        #     numbers by `loop.index`, so dropping the element would silently
        #     RENUMBER and re-point the prose at the WRONG source. Measured on
        #     the 4 affected prod rows: filtering mis-points all four.
        #   * no credibility pill, and no source label claiming a source.
        # Removing the rows from the DB instead would hit the same renumbering
        # hazard, so they are deliberately retained as known residue.
        is_tombstone = slug == "local"
        # Rule 19 — apply THE shared transform, the same one the write path uses
        # (`tombstone_citation` above), so a row tombstoned AT WRITE and a row
        # tombstoned AT RENDER are byte-identical on the page. For the 8 stubs in
        # prod this is a no-op (they already carry url='' and their pill is
        # suppressed below), so render output is unchanged — pinned by
        # tests/test_share_local_tombstone.py.
        if is_tombstone:
            c = tombstone_citation(c)

        # No credibility pill (converged on the app, 2026-08-10) and NO per-source
        # colour: `utils/sourceLabels.ts:15-16` — "no source wears a semantic/quality
        # color (the old PubMed success-green was misleading)".
        #
        # The source name renders in a THEMEABLE token, not literal hex, so
        # prefers-color-scheme can reach it. A tombstone is dimmed — that is a STATE
        # distinction, not a source-identity one, and it is what keeps the withdrawn
        # slot legible now that no source carries colour (fly-216 gate row 5).
        source_color = "var(--vela-text-muted)" if is_tombstone else "var(--vela-text-primary)"
        # citations from ChatHistory may not include `snippet`;
        # ShareCreate's payload uses whatever the ChatHistory schema
        # carried. Try a few common keys.
        abstract = (
            c.get("snippet")
            or c.get("abstract")
            or c.get("text")
            or ""
        )
        augmented.append({
            **c,
            "source_type": slug,
            "is_tombstone": is_tombstone,
            # A tombstone names no source — it reads "Source withdrawn", never
            # "Local" (share_renderer) and never "FDA" (sourceLabels.ts:68).
            "source_label": s["sourceWithdrawn"] if is_tombstone else sconf["label"],
            "source_color": source_color,
            "credibility": None if is_tombstone else c.get("credibility"),
            "abstract_truncated": _truncate_abstract(abstract),
        })
        # A tombstone is NOT counted in the source chips — those summarise which
        # sources back the answer, and a withdrawn stub backs nothing.
        if not is_tombstone:
            type_counter[sconf["label"]] += 1

    chips = [
        {"label": label, "count": count}
        for label, count in type_counter.most_common()
    ]
    return augmented, chips


def resolve_locale(requested: str | None) -> str:
    """PHASE A only ships en + zh-TW renderer copy. Anything else → en.

    Note: utils/i18n-share.ts already falls back to en for the other 14
    languages, so the single-locale degradation is consistent end-to-end.
    """
    if requested == "zh-TW":
        return "zh-TW"
    return "en"


def _truncate(text: str, n: int) -> str:
    text = (text or "").strip().replace("\n", " ").replace("\r", " ")
    return text if len(text) <= n else text[: n - 1].rstrip() + "…"


def _base_url() -> str:
    return os.getenv("VELA_PUBLIC_BASE_URL", "https://vela.an-tho.com").rstrip("/")


def _common_context(share, locale: str) -> dict[str, Any]:
    import time as _time

    s = _STRINGS[locale]
    base = _base_url()
    share_id = getattr(share, "share_id", "") if share else ""
    query_text = getattr(share, "query_text", "") if share else ""
    answer_text = getattr(share, "answer_text", "") if share else ""

    return {
        "html_lang": _HTML_LANG_MAP[locale],
        "s": s,
        "share_id": share_id,
        "query_text": query_text,
        "answer_text": answer_text,
        "og_title": _truncate(query_text, 80) + " · Vela" if query_text else "Vela",
        "og_description": _truncate(answer_text, 160),
        "og_image": f"{base}/static/og/{share_id}.png" if share_id else f"{base}/static/og/default.png",
        "canonical_url": f"{base}/q/{share_id}" if share_id else base,
        # PRD § 4.5 PHASE B Step 3 — wall-clock at render time, used by
        # the inline script + the /?from_share landing handler to
        # estimate time_on_page_sec without a server round-trip.
        "render_timestamp_ms": int(_time.time() * 1000),
        "api_base_url": base,
    }


def render_public_page(share, locale: str) -> str:
    locale = resolve_locale(locale)
    ctx = _common_context(share, locale)
    raw_citations = getattr(share, "citations", None) or []
    answer_text = ctx.get("answer_text", "")

    # Pre-split sections + render markdown server-side.
    parsed = parse_research_sections(answer_text)
    sections: list[dict[str, Any]] = []
    for sec in parsed:
        sections.append({
            "title": sec["title"],
            "marker": sec["marker"],
            "border_color": _MARKER_BORDER_COLORS.get(sec["marker"], _MARKER_BORDER_COLORS[None]),
            "html": Markup(_markdown_to_html(sec["content"])),
        })

    augmented, source_chips = _augment_citations(raw_citations, locale)

    ctx["sections"] = sections
    ctx["citations"] = augmented
    ctx["source_chips"] = source_chips
    return _env.get_template("q_public.jinja2").render(**ctx)


def render_revoked_page(locale: str, share=None) -> str:
    locale = resolve_locale(locale)
    ctx = _common_context(share, locale)
    return _env.get_template("q_revoked.jinja2").render(**ctx)


def render_flagged_page(locale: str, share=None) -> str:
    locale = resolve_locale(locale)
    ctx = _common_context(share, locale)
    return _env.get_template("q_flagged.jinja2").render(**ctx)
