// utils/i18n-share.ts — PRD § 4.5 Share Answer translations.
// Phase 0 coverage: en + zh-TW in full; other 14 languages fall back to en
// (PRD allows progressive i18n rollout; full 16-language pass deferred to PHASE E).

import type { LangCode } from './i18n';

export interface ShareTranslations {
  // Trigger button (mounts beside FeedbackBar on Research / Verify / Explain)
  buttonLabel: string;             // share.button
  buttonDisabledAnon: string;      // share.button.disabled_anon  (anonymous user gate)
  buttonTooltipAnon: string;       // share.button.tooltip_anon

  // Share Modal
  modalTitle: string;              // share.modal.title
  modalWarning: string;            // share.modal.warning  (full warning paragraph)
  modalGenericWarning: string;     // shown when backend returned unknown_locale_fallback=true
  modalConfirm: string;            // share.modal.confirm
  modalCancel: string;             // share.modal.cancel
  modalConsentCheckbox: string;    // share.modal.consent_checkbox
  modalSensitiveBlocked: string;   // share.modal.sensitive_blocked
  modalQuotaBlocked: string;       // 429 daily limit message
  modalGenericError: string;       // catch-all error message
  modalCopyLink: string;           // copy-to-clipboard button (post-creation)
  modalLinkCopied: string;         // toast after copy
  modalShareOn: string;            // label preceding social-share icon row

  // Public Query Page
  publicCtaTitle: string;          // share.public.cta_title
  publicCtaButton: string;         // share.public.cta_button
  publicDisclaimer: string;        // share.public.disclaimer
  publicRevoked: string;           // share.public.revoked
  publicFlagged: string;           // share.public.flagged

  // Settings: 我的分享 tab
  settingsTabTitle: string;        // share.settings.tab_title
  settingsRevokeButton: string;    // share.settings.revoke_button
  settingsRevokeConfirm: string;   // confirm-revoke prompt
  settingsEmpty: string;           // empty state when no shares
}

const en: ShareTranslations = {
  buttonLabel: 'Share',
  buttonDisabledAnon: 'Sign up to share',
  buttonTooltipAnon: 'Sharing is available for registered users.',

  modalTitle: 'Share this answer publicly',
  modalWarning:
    'Anyone with the link can view this question and answer. Do not share if it contains patient identifiers or any private information. Vela may remove shared content that violates our terms.',
  modalGenericWarning:
    'Automated sensitivity checks for your language are limited — please review the question carefully before sharing.',
  modalConfirm: 'Create public link',
  modalCancel: 'Cancel',
  modalConsentCheckbox:
    'I confirm this question contains no patient name, ID number, medical record number, insurance number, or any information that could identify a specific patient — and I understand that once shared, this content will be publicly visible and cannot be fully recalled.',
  modalSensitiveBlocked:
    'This question may contain personal information and cannot be shared publicly.',
  modalQuotaBlocked: 'Daily share limit reached. Try again later.',
  modalGenericError: 'Could not create share link. Please try again.',
  modalCopyLink: 'Copy link',
  modalLinkCopied: 'Link copied',
  modalShareOn: 'Share on',

  publicCtaTitle: 'Want to ask your own version?',
  publicCtaButton: 'Try it on Vela',
  publicDisclaimer:
    'This content is generated by AI from publicly available medical literature, intended for healthcare professionals as a discussion reference only. It does not constitute medical advice, diagnosis, or prescription. Do not use for self-diagnosis or self-medication. Consult a qualified healthcare provider for any health concerns.',
  publicRevoked: 'This share has been revoked.',
  publicFlagged: 'This share was removed for violating the terms of service.',

  settingsTabTitle: 'My shares',
  settingsRevokeButton: 'Revoke',
  settingsRevokeConfirm: 'Revoke this public link? New visitors will see a revoked notice, but preview cards already cached by social platforms or other parties may continue to display for some time.',
  settingsEmpty: "You haven't shared anything yet.",
};

const zhTW: ShareTranslations = {
  buttonLabel: '分享',
  buttonDisabledAnon: '註冊以分享',
  buttonTooltipAnon: '分享功能僅供註冊使用者使用。',

  modalTitle: '公開分享這個答案',
  modalWarning:
    '任何取得連結的人都可以看到這個問題與答案。請勿分享含病患可識別資訊或任何私人資料的內容。Vela 保留移除違反使用條款內容的權利。',
  modalGenericWarning: '此語言的自動敏感資訊檢查有限,請仔細檢查問題後再分享。',
  modalConfirm: '產生公開連結',
  modalCancel: '取消',
  modalConsentCheckbox: '我已確認此問題不含病患姓名、身分證字號、病歷號、健保號或任何可指向特定病患的資訊,並理解分享後此內容將公開可見且無法完全收回。',
  modalSensitiveBlocked: '此問題可能含個資,無法公開分享',
  modalQuotaBlocked: '今日分享次數已達上限,請稍後再試。',
  modalGenericError: '無法產生分享連結,請稍後再試。',
  modalCopyLink: '複製連結',
  modalLinkCopied: '已複製連結',
  modalShareOn: '分享至',

  publicCtaTitle: '想問你自己的版本?',
  publicCtaButton: '在 Vela 試試',
  publicDisclaimer: '此內容由 AI 根據公開醫學文獻生成,僅供醫療專業人員參考討論,不構成醫療建議、診斷或處方。請勿用於自我診斷或自我用藥。如有健康問題請諮詢合格醫療人員。',
  publicRevoked: '此分享已被撤回',
  publicFlagged: '此分享因違反使用條款已下架',

  settingsTabTitle: '我的分享',
  settingsRevokeButton: '撤回',
  settingsRevokeConfirm: '要撤回此公開連結嗎?新訪客會看到「已撤回」訊息,但已被社群平台或他人快取的預覽卡片可能繼續顯示一段時間。',
  settingsEmpty: '你還沒有任何公開分享。',
};

export function getShare(lang: LangCode): ShareTranslations {
  if (lang === 'zh-TW') return zhTW;
  return en;
}
