"""Server-side localized strings for PRD § 4.6 SEO Explore Pages.

Mirrors `api/i18n/verify_strings.py` shape. en + zh-TW are first-class
hand-translated; the other 14 locales are machine-baseline (same
rationale as the §4.5 PHASE A i18n rollout) and TECH_DEBT will track
native-speaker review pending status.

16 languages: en, zh-TW, zh-CN, ja, ko, es, fr, de, it, pt, th, ar,
hi, bn, he, vi.
"""

from typing import Dict


# Each locale provides the same key set:
#   cta_banner_title, cta_banner_button,
#   breadcrumb_home, breadcrumb_explore,
#   related_queries_title,
#   publicDisclaimer, publicShortDisclaimer,
#   citationsHeading, viewSource,
#   headerTagline, privacyLink, termsLink

EXPLORE_STRINGS: Dict[str, Dict[str, str]] = {
    "en": {
        "cta_banner_title": "Want to ask your own version?",
        "cta_banner_button": "Try in Vela",
        "breadcrumb_home": "Vela",
        "breadcrumb_explore": "Explore",
        "related_queries_title": "Related queries",
        "related_queries_locale_badge_fmt": "(in {locale_name})",
        "category_listing_title": "{category} pages",
        "category_listing_empty": "No pages in this category yet.",
        "publicDisclaimer": (
            "This content is generated by AI from publicly available medical "
            "literature, intended for healthcare professionals as a discussion "
            "reference only. It does not constitute medical advice, diagnosis, "
            "or prescription. Do not use for self-diagnosis or self-medication. "
            "Consult a qualified healthcare provider for any health concerns."
        ),
        "publicShortDisclaimer": (
            "⚠️ For informational purposes only. Always verify with "
            "clinical guidelines and consult a qualified professional."
        ),
        "citationsHeading": "References",
        "viewSource": "View source",
        "headerTagline": "Ask in your language. Verified by official sources.",
        "privacyLink": "Privacy",
        "termsLink": "Terms",
    },
    "zh-TW": {
        "cta_banner_title": "想問你自己的版本?",
        "cta_banner_button": "在 Vela 試試",
        "breadcrumb_home": "Vela",
        "breadcrumb_explore": "探索",
        "related_queries_title": "相關查詢",
        "related_queries_locale_badge_fmt": "(以 {locale_name})",
        "category_listing_title": "{category} 頁面",
        "category_listing_empty": "此分類目前無頁面。",
        "publicDisclaimer": (
            "此內容由 AI 根據公開醫學文獻生成,僅供醫療專業人員參考討論,"
            "不構成醫療建議、診斷或處方。請勿用於自我診斷或自我用藥。"
            "如有健康問題請諮詢合格醫療人員。"
        ),
        "publicShortDisclaimer": (
            "⚠️ 本資訊僅供參考,請依據臨床指引並諮詢合格專業人員。"
        ),
        "citationsHeading": "參考來源",
        "viewSource": "檢視來源",
        "headerTagline": "用你的語言提問,由官方來源驗證。",
        "privacyLink": "隱私政策",
        "termsLink": "使用條款",
    },
    "zh-CN": {
        "cta_banner_title": "想问你自己的版本？",
        "cta_banner_button": "在 Vela 试试",
        "breadcrumb_home": "Vela",
        "breadcrumb_explore": "探索",
        "related_queries_title": "相关查询",
        "related_queries_locale_badge_fmt": "(以 {locale_name})",
        "category_listing_title": "{category} 页面",
        "category_listing_empty": "此分类目前无页面。",
        "publicDisclaimer": (
            "此内容由 AI 根据公开医学文献生成，仅供医疗专业人员参考讨论，"
            "不构成医疗建议、诊断或处方。请勿用于自我诊断或自我用药。"
            "如有健康问题请咨询合格医疗人员。"
        ),
        "publicShortDisclaimer": (
            "⚠️ 本信息仅供参考，请依据临床指南并咨询合格专业人员。"
        ),
        "citationsHeading": "参考来源",
        "viewSource": "查看来源",
        "headerTagline": "用你的语言提问，由官方来源验证。",
        "privacyLink": "隐私政策",
        "termsLink": "使用条款",
    },
    "ja": {
        "cta_banner_title": "あなた自身の質問もしてみませんか？",
        "cta_banner_button": "Vela で試す",
        "breadcrumb_home": "Vela",
        "breadcrumb_explore": "探索",
        "related_queries_title": "関連する質問",
        "related_queries_locale_badge_fmt": "（{locale_name}）",
        "category_listing_title": "{category} ページ",
        "category_listing_empty": "このカテゴリーにはまだページがありません。",
        "publicDisclaimer": (
            "本コンテンツは AI が公開医学文献から生成しており、医療専門家の"
            "参考としてのみ使用されることを意図しています。医療アドバイス、"
            "診断、処方には該当しません。自己診断・自己投薬には使用しないで"
            "ください。健康上の懸念がある場合は資格を持つ医療従事者にご相談"
            "ください。"
        ),
        "publicShortDisclaimer": (
            "⚠️ 本情報は参考用です。臨床ガイドラインを確認し、資格のある医療専門家にご相談ください。"
        ),
        "citationsHeading": "参考文献",
        "viewSource": "情報源を見る",
        "headerTagline": "あなたの言語で質問。公式情報源で検証。",
        "privacyLink": "プライバシー",
        "termsLink": "利用規約",
    },
    "ko": {
        "cta_banner_title": "본인의 질문도 해보시겠습니까?",
        "cta_banner_button": "Vela 에서 시도",
        "breadcrumb_home": "Vela",
        "breadcrumb_explore": "탐색",
        "related_queries_title": "관련 질문",
        "related_queries_locale_badge_fmt": "({locale_name})",
        "category_listing_title": "{category} 페이지",
        "category_listing_empty": "이 카테고리에는 아직 페이지가 없습니다.",
        "publicDisclaimer": (
            "이 콘텐츠는 AI가 공개 의학 문헌에서 생성한 것이며, 의료 전문가의 "
            "참고용으로만 사용됩니다. 의료 조언, 진단 또는 처방을 구성하지 "
            "않습니다. 자가 진단 또는 자가 투약에 사용하지 마십시오. 건강 "
            "문제는 자격을 갖춘 의료 제공자와 상의하십시오."
        ),
        "publicShortDisclaimer": (
            "⚠️ 본 정보는 참고용입니다. 임상 지침을 확인하고 자격을 갖춘 의료 전문가와 상담하십시오."
        ),
        "citationsHeading": "참고 문헌",
        "viewSource": "출처 보기",
        "headerTagline": "당신의 언어로 질문. 공식 출처로 검증.",
        "privacyLink": "개인정보",
        "termsLink": "이용 약관",
    },
    "es": {
        "cta_banner_title": "¿Quieres preguntar tu propia versión?",
        "cta_banner_button": "Probar en Vela",
        "breadcrumb_home": "Vela",
        "breadcrumb_explore": "Explorar",
        "related_queries_title": "Consultas relacionadas",
        "related_queries_locale_badge_fmt": "(en {locale_name})",
        "category_listing_title": "Páginas de {category}",
        "category_listing_empty": "Aún no hay páginas en esta categoría.",
        "publicDisclaimer": (
            "Este contenido es generado por IA a partir de literatura médica "
            "públicamente disponible, destinado a profesionales sanitarios "
            "como referencia. No constituye consejo médico, diagnóstico ni "
            "prescripción. No utilizar para autodiagnóstico ni automedicación. "
            "Consulte a un profesional sanitario cualificado."
        ),
        "publicShortDisclaimer": (
            "⚠️ Solo con fines informativos. Verifique con las guías clínicas y consulte a un profesional cualificado."
        ),
        "citationsHeading": "Referencias",
        "viewSource": "Ver fuente",
        "headerTagline": "Pregunta en tu idioma. Verificado por fuentes oficiales.",
        "privacyLink": "Privacidad",
        "termsLink": "Términos",
    },
    "fr": {
        "cta_banner_title": "Voulez-vous poser votre propre version ?",
        "cta_banner_button": "Essayer Vela",
        "breadcrumb_home": "Vela",
        "breadcrumb_explore": "Explorer",
        "related_queries_title": "Requêtes associées",
        "related_queries_locale_badge_fmt": "(en {locale_name})",
        "category_listing_title": "Pages {category}",
        "category_listing_empty": "Aucune page dans cette catégorie pour l'instant.",
        "publicDisclaimer": (
            "Ce contenu est généré par l'IA à partir de la littérature médicale "
            "publiquement disponible, destiné aux professionnels de santé comme "
            "référence. Il ne constitue pas un avis médical, un diagnostic ou "
            "une prescription. Ne pas utiliser pour l'auto-diagnostic ou "
            "l'auto-médication. Consultez un professionnel de santé qualifié."
        ),
        "publicShortDisclaimer": (
            "⚠️ À titre informatif uniquement. Vérifiez avec les directives cliniques et consultez un professionnel qualifié."
        ),
        "citationsHeading": "Références",
        "viewSource": "Voir la source",
        "headerTagline": "Posez votre question. Vérifié par sources officielles.",
        "privacyLink": "Confidentialité",
        "termsLink": "Conditions",
    },
    "de": {
        "cta_banner_title": "Möchten Sie Ihre eigene Version fragen?",
        "cta_banner_button": "In Vela versuchen",
        "breadcrumb_home": "Vela",
        "breadcrumb_explore": "Erkunden",
        "related_queries_title": "Verwandte Anfragen",
        "related_queries_locale_badge_fmt": "(auf {locale_name})",
        "category_listing_title": "{category}-Seiten",
        "category_listing_empty": "Noch keine Seiten in dieser Kategorie.",
        "publicDisclaimer": (
            "Dieser Inhalt wird von KI aus öffentlich verfügbarer medizinischer "
            "Literatur generiert und richtet sich an medizinisches Fachpersonal "
            "als Referenz. Er stellt keine medizinische Beratung, Diagnose oder "
            "Verschreibung dar. Nicht zur Selbstdiagnose oder Selbstmedikation "
            "verwenden. Konsultieren Sie einen qualifizierten Arzt."
        ),
        "publicShortDisclaimer": (
            "⚠️ Nur zu Informationszwecken. Überprüfen Sie die klinischen Leitlinien und konsultieren Sie einen qualifizierten Fachmann."
        ),
        "citationsHeading": "Referenzen",
        "viewSource": "Quelle ansehen",
        "headerTagline": "Fragen Sie in Ihrer Sprache. Geprüft durch offizielle Quellen.",
        "privacyLink": "Datenschutz",
        "termsLink": "Bedingungen",
    },
    "it": {
        "cta_banner_title": "Vuoi porre la tua versione?",
        "cta_banner_button": "Prova in Vela",
        "breadcrumb_home": "Vela",
        "breadcrumb_explore": "Esplora",
        "related_queries_title": "Domande correlate",
        "related_queries_locale_badge_fmt": "(in {locale_name})",
        "category_listing_title": "Pagine {category}",
        "category_listing_empty": "Ancora nessuna pagina in questa categoria.",
        "publicDisclaimer": (
            "Questo contenuto è generato dall'IA da letteratura medica "
            "pubblicamente disponibile, destinato ai professionisti sanitari "
            "come riferimento. Non costituisce consulenza medica, diagnosi o "
            "prescrizione. Non utilizzare per autodiagnosi o automedicazione. "
            "Consultare un operatore sanitario qualificato."
        ),
        "publicShortDisclaimer": (
            "⚠️ Solo a scopo informativo. Verificare con le linee guida cliniche e consultare un professionista qualificato."
        ),
        "citationsHeading": "Riferimenti",
        "viewSource": "Vedi la fonte",
        "headerTagline": "Chiedi nella tua lingua. Verificato da fonti ufficiali.",
        "privacyLink": "Privacy",
        "termsLink": "Termini",
    },
    "pt": {
        "cta_banner_title": "Quer fazer sua própria pergunta?",
        "cta_banner_button": "Experimentar Vela",
        "breadcrumb_home": "Vela",
        "breadcrumb_explore": "Explorar",
        "related_queries_title": "Consultas relacionadas",
        "related_queries_locale_badge_fmt": "(em {locale_name})",
        "category_listing_title": "Páginas de {category}",
        "category_listing_empty": "Ainda não há páginas nesta categoria.",
        "publicDisclaimer": (
            "Este conteúdo é gerado por IA a partir de literatura médica "
            "publicamente disponível, destinado a profissionais de saúde como "
            "referência. Não constitui aconselhamento médico, diagnóstico ou "
            "prescrição. Não usar para autodiagnóstico ou automedicação. "
            "Consulte um profissional de saúde qualificado."
        ),
        "publicShortDisclaimer": (
            "⚠️ Apenas para fins informativos. Verifique com as diretrizes clínicas e consulte um profissional qualificado."
        ),
        "citationsHeading": "Referências",
        "viewSource": "Ver fonte",
        "headerTagline": "Pergunte no seu idioma. Verificado por fontes oficiais.",
        "privacyLink": "Privacidade",
        "termsLink": "Termos",
    },
    "th": {
        "cta_banner_title": "ต้องการถามเวอร์ชั่นของคุณเองหรือไม่?",
        "cta_banner_button": "ลองใน Vela",
        "breadcrumb_home": "Vela",
        "breadcrumb_explore": "สำรวจ",
        "related_queries_title": "คำถามที่เกี่ยวข้อง",
        "related_queries_locale_badge_fmt": "(ภาษา {locale_name})",
        "category_listing_title": "หน้า {category}",
        "category_listing_empty": "ยังไม่มีหน้าในหมวดหมู่นี้",
        "publicDisclaimer": (
            "เนื้อหานี้สร้างโดย AI จากวรรณกรรมทางการแพทย์ที่เปิดเผยต่อสาธารณะ "
            "มีวัตถุประสงค์เพื่อใช้เป็นข้อมูลอ้างอิงสำหรับบุคลากรทางการแพทย์เท่านั้น "
            "ไม่ถือเป็นคำแนะนำทางการแพทย์ การวินิจฉัย หรือใบสั่งยา "
            "ห้ามใช้สำหรับการวินิจฉัยตนเองหรือการใช้ยาด้วยตนเอง "
            "โปรดปรึกษาผู้ให้บริการด้านสุขภาพที่มีคุณสมบัติ"
        ),
        "publicShortDisclaimer": (
            "⚠️ ข้อมูลนี้ใช้เพื่อการอ้างอิงเท่านั้น กรุณาตรวจสอบตามแนวทางปฏิบัติทางคลินิกและปรึกษาผู้เชี่ยวชาญที่มีคุณสมบัติ"
        ),
        "citationsHeading": "เอกสารอ้างอิง",
        "viewSource": "ดูแหล่งที่มา",
        "headerTagline": "ถามในภาษาของคุณ ตรวจสอบโดยแหล่งทางการ",
        "privacyLink": "ความเป็นส่วนตัว",
        "termsLink": "ข้อกำหนด",
    },
    "ar": {
        "cta_banner_title": "هل تريد طرح نسختك الخاصة؟",
        "cta_banner_button": "جرب في Vela",
        "breadcrumb_home": "Vela",
        "breadcrumb_explore": "استكشاف",
        "related_queries_title": "استفسارات ذات صلة",
        "related_queries_locale_badge_fmt": "(بـ {locale_name})",
        "category_listing_title": "صفحات {category}",
        "category_listing_empty": "لا توجد صفحات في هذه الفئة بعد.",
        "publicDisclaimer": (
            "تم إنشاء هذا المحتوى بواسطة الذكاء الاصطناعي من الأدبيات الطبية "
            "المتاحة للجمهور، وهو مخصص للمتخصصين في الرعاية الصحية كمرجع فقط. "
            "لا يشكل نصيحة طبية أو تشخيصاً أو وصفة طبية. لا تستخدمه للتشخيص الذاتي "
            "أو العلاج الذاتي. استشر مقدم رعاية صحية مؤهلاً."
        ),
        "publicShortDisclaimer": (
            "⚠️ هذه المعلومات للأغراض المرجعية فقط. يرجى التحقق من الإرشادات السريرية واستشارة متخصص مؤهل."
        ),
        "citationsHeading": "المراجع",
        "viewSource": "عرض المصدر",
        "headerTagline": "اسأل بلغتك. تم التحقق من المصادر الرسمية.",
        "privacyLink": "الخصوصية",
        "termsLink": "الشروط",
    },
    "hi": {
        "cta_banner_title": "अपना खुद का संस्करण पूछना चाहते हैं?",
        "cta_banner_button": "Vela में आज़माएं",
        "breadcrumb_home": "Vela",
        "breadcrumb_explore": "खोजें",
        "related_queries_title": "संबंधित प्रश्न",
        "related_queries_locale_badge_fmt": "({locale_name} में)",
        "category_listing_title": "{category} पृष्ठ",
        "category_listing_empty": "इस श्रेणी में अभी तक कोई पृष्ठ नहीं है।",
        "publicDisclaimer": (
            "यह सामग्री AI द्वारा सार्वजनिक रूप से उपलब्ध चिकित्सा साहित्य से उत्पन्न की गई है, "
            "जो स्वास्थ्य पेशेवरों के लिए केवल चर्चा संदर्भ के रूप में है। यह चिकित्सा सलाह, "
            "निदान या नुस्खे का गठन नहीं करता है। स्व-निदान या स्व-औषधि के लिए उपयोग न करें। "
            "किसी भी स्वास्थ्य चिंता के लिए योग्य स्वास्थ्य प्रदाता से परामर्श करें।"
        ),
        "publicShortDisclaimer": (
            "⚠️ यह जानकारी केवल संदर्भ उद्देश्यों के लिए है। कृपया नैदानिक दिशानिर्देशों से सत्यापित करें और किसी योग्य पेशेवर से परामर्श करें।"
        ),
        "citationsHeading": "संदर्भ",
        "viewSource": "स्रोत देखें",
        "headerTagline": "अपनी भाषा में पूछें। आधिकारिक स्रोतों द्वारा सत्यापित।",
        "privacyLink": "गोपनीयता",
        "termsLink": "शर्तें",
    },
    "bn": {
        "cta_banner_title": "নিজের প্রশ্ন করতে চান?",
        "cta_banner_button": "Vela তে চেষ্টা করুন",
        "breadcrumb_home": "Vela",
        "breadcrumb_explore": "অনুসন্ধান",
        "related_queries_title": "সম্পর্কিত প্রশ্ন",
        "related_queries_locale_badge_fmt": "({locale_name}-এ)",
        "category_listing_title": "{category} পৃষ্ঠা",
        "category_listing_empty": "এই বিভাগে এখনও কোনও পৃষ্ঠা নেই।",
        "publicDisclaimer": (
            "এই বিষয়বস্তু সর্বজনীনভাবে উপলব্ধ চিকিৎসা সাহিত্য থেকে AI দ্বারা উৎপন্ন, "
            "শুধুমাত্র চিকিৎসা পেশাদারদের জন্য আলোচনার রেফারেন্স হিসাবে। এটি চিকিৎসা পরামর্শ, "
            "রোগ নির্ণয় বা প্রেসক্রিপশন গঠন করে না। স্ব-নির্ণয় বা স্ব-চিকিৎসার জন্য ব্যবহার করবেন না। "
            "যেকোনো স্বাস্থ্য সমস্যার জন্য যোগ্য স্বাস্থ্যসেবা প্রদানকারীর সাথে পরামর্শ করুন।"
        ),
        "publicShortDisclaimer": (
            "⚠️ এই তথ্য শুধুমাত্র তথ্যসূত্র উদ্দেশ্যে। অনুগ্রহ করে ক্লিনিক্যাল নির্দেশিকা যাচাই করুন এবং একজন যোগ্য পেশাদারের সাথে পরামর্শ করুন।"
        ),
        "citationsHeading": "তথ্যসূত্র",
        "viewSource": "উৎস দেখুন",
        "headerTagline": "আপনার ভাষায় জিজ্ঞাসা করুন। সরকারি সূত্র দ্বারা যাচাইকৃত।",
        "privacyLink": "গোপনীয়তা",
        "termsLink": "শর্তাবলী",
    },
    "he": {
        "cta_banner_title": "רוצה לשאול את הגרסה שלך?",
        "cta_banner_button": "נסה ב-Vela",
        "breadcrumb_home": "Vela",
        "breadcrumb_explore": "חקור",
        "related_queries_title": "שאילתות קשורות",
        "related_queries_locale_badge_fmt": "(ב{locale_name})",
        "category_listing_title": "דפי {category}",
        "category_listing_empty": "אין עדיין דפים בקטגוריה זו.",
        "publicDisclaimer": (
            "תוכן זה נוצר על ידי AI מספרות רפואית הזמינה לציבור, מיועד לאנשי "
            "מקצוע בתחום הבריאות כהפניה בלבד. אינו מהווה ייעוץ רפואי, אבחנה "
            "או מרשם. אין להשתמש לאבחון עצמי או טיפול עצמי. התייעצו עם איש "
            "מקצוע מוסמך לכל בעיה בריאותית."
        ),
        "publicShortDisclaimer": (
            "⚠️ מידע זה מיועד לצורכי עיון בלבד. אנא אמתו מול הנחיות קליניות והתייעצו עם איש מקצוע מוסמך."
        ),
        "citationsHeading": "הפניות",
        "viewSource": "צפה במקור",
        "headerTagline": "שאל בשפה שלך. מאומת ממקורות רשמיים.",
        "privacyLink": "פרטיות",
        "termsLink": "תנאים",
    },
    "vi": {
        "cta_banner_title": "Bạn có muốn đặt phiên bản của riêng mình không?",
        "cta_banner_button": "Thử Vela",
        "breadcrumb_home": "Vela",
        "breadcrumb_explore": "Khám phá",
        "related_queries_title": "Truy vấn liên quan",
        "related_queries_locale_badge_fmt": "(bằng {locale_name})",
        "category_listing_title": "Trang {category}",
        "category_listing_empty": "Chưa có trang nào trong danh mục này.",
        "publicDisclaimer": (
            "Nội dung này được tạo bởi AI từ tài liệu y khoa công khai, dành cho "
            "các chuyên gia chăm sóc sức khỏe chỉ làm tài liệu tham khảo. Không "
            "phải lời khuyên y tế, chẩn đoán hoặc đơn thuốc. Không tự chẩn đoán "
            "hay tự dùng thuốc. Tham khảo ý kiến chuyên gia y tế có trình độ."
        ),
        "publicShortDisclaimer": (
            "⚠️ Thông tin này chỉ mang tính chất tham khảo. Vui lòng kiểm tra theo hướng dẫn lâm sàng và tham khảo ý kiến chuyên gia có trình độ."
        ),
        "citationsHeading": "Tài liệu tham khảo",
        "viewSource": "Xem nguồn",
        "headerTagline": "Hỏi bằng ngôn ngữ của bạn. Được xác minh bởi các nguồn chính thức.",
        "privacyLink": "Quyền riêng tư",
        "termsLink": "Điều khoản",
    },
}


def get_explore_strings(locale: str) -> Dict[str, str]:
    """Return the full string dict for a locale; fall back to en if
    the locale isn't one of the 16 first-class."""
    return EXPLORE_STRINGS.get(locale) or EXPLORE_STRINGS["en"]


def get_explore_string(key: str, locale: str) -> str:
    """Return a single key from the locale dict; fall back to en, then
    to the literal key if even en is missing."""
    bundle = get_explore_strings(locale)
    return bundle.get(key) or EXPLORE_STRINGS["en"].get(key) or key
